### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by primoz-k** [PoslinskiNet/ember-introjs#13]
Is there any chance for you to create a release, so I can use the Ember 2.0 compatible version of this library in bower.json dependencies?

**Comment by primoz-k** [comment]
Oh, I just saw an open issue about this, my bad.

**Comment by Robdel12** [comment]
If you'd like to take this addon over we're looking for a new owner :)

**Comment by primoz-k** [comment]
I'm still a little noobish when it comes to Ember, so maybe not right now.

But I like this library over similar ones, because it looks simple to use and it's really a shame I can't use it in my project. I hope someone will volounteer and take this addon over :)

**Comment by Exelord** [comment]
Hi @Robdel12,
Together with @poslinskiNet we are using this package in our project. We have almost 2 years of experience in Ember and If you wish we could maintain this project. Especially now, when the latest ember-cli makes this package deprecated.

**Comment by Robdel12** [comment]
Hi @Exelord! That's great news. 

@cowboyd wanna pass this project along?

**Comment by cowboyd** [comment]
Transfer request sent!

**Comment by PoslinskiNet** [comment]
@cowboyd Great 👍  However, I can't see any notification about ownership transfer yet.

**Comment by Robdel12** [comment]
Ah I think we sent it to @Exelord

**Comment by Exelord** [comment]
Thanks, guys. We will take care of that :)
@PoslinskiNet will take the ownership. Until the end of next week, we should make it up to date and fully compatible with the latest ember-cli.
