### ISSUE TITLE
intro-js/step not found

### ISSUE THREAD

**Issue by TAFrew** [PoslinskiNet/ember-introjs#20]
Hi, I have recently downloaded and followed your readme but when I try to use it I get the following error:

Uncaught Error: Assertion Failed: A component or helper named "intro-js/step" could not be found.

Do you have any idea what could be causing this?

**Comment by Exelord** [comment]
Sorry, this component was not released yet :/ A proper PR has been opened.

**Comment by PoslinskiNet** [comment]
You can use it now from version 2.1.0 @TAFrew. Thanks @Exelord 👍
