### ISSUE TITLE
Closure actions instead of normal actions?

### ISSUE THREAD

**Issue by Kuzirashi** [PoslinskiNet/ember-introjs#26]
Is it possible to use closure actions instead of passing action string?

**Comment by PoslinskiNet** [comment]
@Kuzirashi What would you like to achieve?

I think there shouldn't be a problem, please take a look at the Twiddle:

https://ember-twiddle.com/ab6b472fa89b78b9446545e8ef193b0b?openFiles=templates.application.hbs%2C
