### ISSUE TITLE
Index js errors when running on ember engines 

### ISSUE THREAD

**Issue by rspraveenraj** [PoslinskiNet/ember-introjs#27]
I have a ember engine setup with the intro js defined in each of the engines and the parent application , Everything works fine on the parent application but when I try to access intro js on the engine instance I get a build error , it's gives me an error 'cannot access project of undefined ' in the method introjspath .

**Comment by PoslinskiNet** [comment]
@rspraveenraj Could you provide ember twiddle example with this case?

**Comment by Exelord** [comment]
@PoslinskiNet  This happens because `this.app.project.nodeModules` is not available in ember-engine :/

**Comment by rspraveenraj** [comment]
In the included function as a workaround I did a
this.app=this.app?this.app:app and it worked , not sure if that's the
correct way to do it .

**Comment by PoslinskiNet** [comment]
Hey @rspraveenraj. Could you verify is it working fine now without your workaround (with the newest version)?

**Comment by PoslinskiNet** [comment]
I'm closing this since it seems to be resolved. Please create a new issue in case of the similar problem with the current version of the addon.
