### ISSUE TITLE
'steps' property may be invalid

### ISSUE THREAD

**Issue by Ghostubborn** [PoslinskiNet/ember-introjs#28]
https://github.com/PoslinskiNet/ember-introjs#1-declare-your-steps
This section seems useless, intro can't find the elements that defined in controller.

**Comment by PoslinskiNet** [comment]
Thanks for the catch @Ghostubborn. It was confusing a little. I've updated README so now it should be easier to determinate the fact, that there are 2 different approaches to use this package to get an intro in your application.
