### ISSUE TITLE
Error: Compile Error: intro-js is not a helper

### ISSUE THREAD

**Issue by gfmartinez** [PoslinskiNet/ember-introjs#94]
Installed the add-on

`{{#intro-js/step ...}}{{/intro-js/step}}`
Works fine.

But as recommended, the `{{intro-js start-if=true}}` gives the `Error: Compile Error: intro-js is not a helper`

I'm probably doing something wrong :)

**Comment by PoslinskiNet** [comment]
Is it possible that you are using pods structure? If so, then I need to apply small changes in file structure to make pods oriented projects 💚again.

**Comment by gfmartinez** [comment]
@PoslinskiNet Thanks so much for quick reply. Yes, I'm using pods.

**Comment by PoslinskiNet** [comment]
@gfmartinez I've published the potential fix. Could you test with `2.5.1` ?

**Comment by gfmartinez** [comment]
@PoslinskiNet That worked. Thank you so much!!!!
