### ISSUE TITLE
Error during ember install

### ISSUE THREAD

**Issue by dragoon000320** [PoslinskiNet/ember-introjs#99]
Hi, i had an issue while installing your module, here is a traceback from cli:

Command failed: yarn add --dev ember-introjs --non-interactive
error ember-cli-babel@6.0.0: The engine "node" is incompatible with this module. Expected version "^4.5 || 6.* || 7.*".
error An unexpected error occurred: "Found incompatible module".

yarn add v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info If you think this is a bug, please open a bug report with the information provided in "yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Stack Trace and Error Report: C:\Users\jarda_pc\AppData\Local\Temp/error.dump.08932908a9284f0d46a9fd6ca015a67f.log
a9fd6ca015a67f.log

Can you please, help me with an issue? Thanks in advance

**Comment by PoslinskiNet** [comment]
Could you check in your terminal the node version via `node -v` command? It looks like an incompatibility issue.

**Comment by dragoon000320** [comment]
i solved it by --ignore-engines option during installation. No issues have been met since then.
